name: Python DevSecOps Pipeline

on:
  push:

  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:

  ci:
    name: CI Pipeline
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.11]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}

          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8
        run: flake8 app/main.py

      - name: Run Unit Tests
        run: PYTHONPATH=. pytest tests/test_main.py

      - name: Build Python Package
        run: python -m build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:     
          name: python-package-${{ matrix.python-version }}
          path: dist/

# =========================================================
# SECURITY SCAN
# =========================================================

  security_scan:
    name: Trivy Security Scan
    runs-on: self-hosted

    needs: ci

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@v0.35.0

        with:
          scan-type: 'fs'
          scan-ref: '.'

          format: 'sarif'
          output: 'vuln-result.sarif'

          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: Upload Trivy Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3

        with:
          sarif_file: 'vuln-result.sarif'


# =========================================================
# APPLICATION DEPLOYMENT
# =========================================================

  deploy:
    name: Deploy Application
    runs-on: self-hosted

    needs: security_scan

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Linux VM
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}

          script: |
            echo "Starting deployment..."

            if [ ! -d "/opt/python-devops-project" ]; then
              sudo git clone https://github.com/${{ github.repository }} /opt/python-devops-project
            fi

            sudo chown -R $VM_USERNAME:$VM_USERNAME /opt/python-devops-project

            cd /opt/python-devops-project

            sudo git pull origin main

            sudo python3 -m venv venv

            source venv/bin/activate

            pip install -r requirements.txt

            sudo tee /etc/systemd/system/flaskapp.service > /dev/null <<EOF
            [Unit]
            Description=Flask Application
            After=network.target

            [Service]
            User=${{ secrets.VM_USERNAME }}
            WorkingDirectory=/opt/python-devops-project

            ExecStart=/opt/python-devops-project/venv/bin/gunicorn \
            --bind 0.0.0.0:5000 \
            app.main:app

            [Install]
            WantedBy=multi-user.target
            EOF

            sudo systemctl daemon-reload

            sudo systemctl enable flaskapp

            sudo systemctl restart flaskapp

            echo "Deployment Successful!"

# =========================================================
# installing the docker inside the self-hosted runner , because appleboy/ssh-action@v1.0.3 github actions needs the docker package on linux vm.
# So actions requires the container to run. Also , add the linux user inot the docker group. So user can run required docker command without root access.
